// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metapb.proto

package raftstorepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import raftpb "go.etcd.io/etcd/raft/v3/raftpb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RaftLocalState struct {
	HardState            *raftpb.HardState `protobuf:"bytes,1,opt,name=hard_state,json=hardState" json:"hard_state,omitempty"`
	LastIndex            uint64            `protobuf:"varint,2,opt,name=last_index,json=lastIndex" json:"last_index,omitempty"`
	LastTerm             uint64            `protobuf:"varint,3,opt,name=last_term,json=lastTerm" json:"last_term,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RaftLocalState) Reset()         { *m = RaftLocalState{} }
func (m *RaftLocalState) String() string { return proto.CompactTextString(m) }
func (*RaftLocalState) ProtoMessage()    {}
func (*RaftLocalState) Descriptor() ([]byte, []int) {
	return fileDescriptor_metapb_7452efb5ca5cd656, []int{0}
}
func (m *RaftLocalState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftLocalState.Unmarshal(m, b)
}
func (m *RaftLocalState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftLocalState.Marshal(b, m, deterministic)
}
func (dst *RaftLocalState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftLocalState.Merge(dst, src)
}
func (m *RaftLocalState) XXX_Size() int {
	return xxx_messageInfo_RaftLocalState.Size(m)
}
func (m *RaftLocalState) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftLocalState.DiscardUnknown(m)
}

var xxx_messageInfo_RaftLocalState proto.InternalMessageInfo

func (m *RaftLocalState) GetHardState() *raftpb.HardState {
	if m != nil {
		return m.HardState
	}
	return nil
}

func (m *RaftLocalState) GetLastIndex() uint64 {
	if m != nil {
		return m.LastIndex
	}
	return 0
}

func (m *RaftLocalState) GetLastTerm() uint64 {
	if m != nil {
		return m.LastTerm
	}
	return 0
}

type RaftApplyState struct {
	ApplyIndex           uint64              `protobuf:"varint,1,opt,name=apply_index,json=applyIndex" json:"apply_index,omitempty"`
	TruncatedState       *RaftTruncatedState `protobuf:"bytes,2,opt,name=truncated_state,json=truncatedState" json:"truncated_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RaftApplyState) Reset()         { *m = RaftApplyState{} }
func (m *RaftApplyState) String() string { return proto.CompactTextString(m) }
func (*RaftApplyState) ProtoMessage()    {}
func (*RaftApplyState) Descriptor() ([]byte, []int) {
	return fileDescriptor_metapb_7452efb5ca5cd656, []int{1}
}
func (m *RaftApplyState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftApplyState.Unmarshal(m, b)
}
func (m *RaftApplyState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftApplyState.Marshal(b, m, deterministic)
}
func (dst *RaftApplyState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftApplyState.Merge(dst, src)
}
func (m *RaftApplyState) XXX_Size() int {
	return xxx_messageInfo_RaftApplyState.Size(m)
}
func (m *RaftApplyState) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftApplyState.DiscardUnknown(m)
}

var xxx_messageInfo_RaftApplyState proto.InternalMessageInfo

func (m *RaftApplyState) GetApplyIndex() uint64 {
	if m != nil {
		return m.ApplyIndex
	}
	return 0
}

func (m *RaftApplyState) GetTruncatedState() *RaftTruncatedState {
	if m != nil {
		return m.TruncatedState
	}
	return nil
}

type RaftTruncatedState struct {
	Index                uint64   `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Term                 uint64   `protobuf:"varint,2,opt,name=term" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaftTruncatedState) Reset()         { *m = RaftTruncatedState{} }
func (m *RaftTruncatedState) String() string { return proto.CompactTextString(m) }
func (*RaftTruncatedState) ProtoMessage()    {}
func (*RaftTruncatedState) Descriptor() ([]byte, []int) {
	return fileDescriptor_metapb_7452efb5ca5cd656, []int{2}
}
func (m *RaftTruncatedState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftTruncatedState.Unmarshal(m, b)
}
func (m *RaftTruncatedState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftTruncatedState.Marshal(b, m, deterministic)
}
func (dst *RaftTruncatedState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftTruncatedState.Merge(dst, src)
}
func (m *RaftTruncatedState) XXX_Size() int {
	return xxx_messageInfo_RaftTruncatedState.Size(m)
}
func (m *RaftTruncatedState) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftTruncatedState.DiscardUnknown(m)
}

var xxx_messageInfo_RaftTruncatedState proto.InternalMessageInfo

func (m *RaftTruncatedState) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *RaftTruncatedState) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func init() {
	proto.RegisterType((*RaftLocalState)(nil), "raftstorepb.RaftLocalState")
	proto.RegisterType((*RaftApplyState)(nil), "raftstorepb.RaftApplyState")
	proto.RegisterType((*RaftTruncatedState)(nil), "raftstorepb.RaftTruncatedState")
}

func init() { proto.RegisterFile("metapb.proto", fileDescriptor_metapb_7452efb5ca5cd656) }

var fileDescriptor_metapb_7452efb5ca5cd656 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0x41, 0x4b, 0xc3, 0x50,
	0x0c, 0xa6, 0x73, 0x8a, 0x4b, 0x65, 0xe2, 0xc3, 0x43, 0x51, 0x64, 0xa3, 0xa7, 0x79, 0x79, 0x15,
	0x77, 0x17, 0xbc, 0x4d, 0xf0, 0x54, 0x77, 0x2f, 0x69, 0xdf, 0x9b, 0x1b, 0xb4, 0x7b, 0x8f, 0xd7,
	0x28, 0x8a, 0xe0, 0x6f, 0x97, 0x97, 0x58, 0x98, 0x78, 0x4a, 0xbe, 0x2f, 0xc9, 0x97, 0x2f, 0x81,
	0xb3, 0xce, 0x12, 0xfa, 0x5a, 0xfb, 0xe0, 0xc8, 0xa9, 0x34, 0xe0, 0x86, 0x7a, 0x72, 0xc1, 0xfa,
	0xfa, 0xea, 0xf6, 0xd5, 0x69, 0x4b, 0x8d, 0xd1, 0x3b, 0x57, 0xc4, 0x58, 0xc4, 0x62, 0xf1, 0xbe,
	0xe4, 0xe8, 0x6b, 0x0e, 0x32, 0x97, 0x7f, 0xc3, 0xb4, 0xc4, 0x0d, 0x3d, 0xbb, 0x06, 0xdb, 0x17,
	0x42, 0xb2, 0xea, 0x0e, 0x60, 0x8b, 0xc1, 0x54, 0x7d, 0x44, 0x59, 0x32, 0x4f, 0x16, 0xe9, 0xfd,
	0x85, 0x96, 0x49, 0xbd, 0xc2, 0x60, 0xb8, 0xad, 0x9c, 0x6c, 0x87, 0x54, 0xdd, 0x00, 0xb4, 0xd8,
	0x53, 0xb5, 0xdb, 0x1b, 0xfb, 0x91, 0x8d, 0xe6, 0xc9, 0x62, 0x5c, 0x4e, 0x22, 0xf3, 0x14, 0x09,
	0x75, 0x0d, 0x0c, 0x2a, 0xb2, 0xa1, 0xcb, 0x8e, 0xb8, 0x7a, 0x1a, 0x89, 0xb5, 0x0d, 0x5d, 0xfe,
	0x25, 0xfb, 0x1f, 0xbd, 0x6f, 0x3f, 0x45, 0x6d, 0x06, 0x29, 0x46, 0xf4, 0x2b, 0x97, 0xf0, 0x00,
	0x30, 0x25, 0x7a, 0x2b, 0x38, 0xa7, 0xf0, 0xb6, 0x6f, 0x90, 0xec, 0xe0, 0x72, 0xc4, 0x2e, 0x67,
	0xfa, 0xe0, 0x09, 0x3a, 0xca, 0xae, 0x87, 0x3e, 0xf1, 0x3c, 0xa5, 0x3f, 0x38, 0x7f, 0x00, 0xf5,
	0xbf, 0x4b, 0x5d, 0xc2, 0xf1, 0xe1, 0x6a, 0x01, 0x4a, 0xc1, 0x98, 0x0f, 0x90, 0xf3, 0x38, 0xaf,
	0x4f, 0xf8, 0x87, 0xcb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x62, 0xdc, 0x1d, 0x3a, 0x8b, 0x01,
	0x00, 0x00,
}
